### ISSUE TITLE
this kind of search functionality

### ISSUE THREAD

**Issue by diomed** [dogukanayd/basic-vue-data-table#6]
hey

could you maybe make this kind of search functionality:

https://codepen.io/bitkill/pen/BypzBV

where table's categories are prepended, and one can choose [filter] category he'd like to search

**Comment by dogukanayd** [comment]
I am on it.

**Comment by diomed** [comment]
p.s. do you have discord? can we talk?

**Comment by dogukanayd** [comment]
@diomed You can e-mail me any time you want. That would be easier.

**Comment by diomed** [comment]
any luck with integrating this request?

**Comment by diomed** [comment]
any luck with integrating this request?

**Comment by diomed** [comment]
:bangbang:

**Comment by diomed** [comment]
any luck with integrating this request?

 ‼️

**Comment by diomed** [comment]
any luck with integrating this request?

 ‼️

**Comment by diomed** [comment]
any luck with integrating this request? ‼️
--
